### PR TITLE
Add new articles from July

### PR DESCRIPTION
**Pull request by xhero**
I extracted and postprocessed all the new articles, running locally they seem to display ok. I'm not sure about the images? probably we need a separate copy.

### CODE REVIEW

**Comment by HirschSt** [comment]
Thats strange, because I do exactly the same ... see http://lab.rism.info:3367/index.html

**Comment by lpugin** [comment]
@HirschSt it was not clear that you would do this. Please next time let us know so the work is not duplicated. We can use cfeafe5a51b9ce79042e0fb0503dd4db48a9d7e9 (only some links need to be fixed but otherwise it looks good!)

**Comment by HirschSt** [comment]
Sorry, but it was discussed at wednesday that I will add the latest news.

**Comment by lpugin** [comment]
Yes, it was not very clear. Nevermind. If you can just fixed the links within the news that will be perfect.

**Comment by HirschSt** [comment]
ok, I'm working on this

**Pull request closed without merging**
