### PR TITLE
Updates to publications descriptions

### PR DESCRIPTION
**Pull request by jenniferward**
@BaMikusi:  Updating these pages with language for both the RISM Catalog and RISM Online:
https://rism.info/index.html
https://rism.info/publications.html 
https://rism.info/organization/rism-for-libraries.html  (still to do on this page: update "Citing RISM" and "Table of RISM Citation Styles")

### CODE REVIEW

**Comment by jenniferward** [comment]
More updates following feedback/discussion from a librarian.

**Comment by jenniferward** [comment]
Additions as discussed today.

**Review by BaMikusi — APPROVED** [review]
I guess the API of RISM Online offers a new path for those willing to reuse our data and should thus be mentioned here (line 90).

**Review by BaMikusi — APPROVED** [review]
We'll need to see if the statement in line 26 about a "collaboration" will be fine, for Laurent tended to refer to RO as being essentially a product of the DC.

**Review by BaMikusi — APPROVED** [review]
"A/I was added to the online RISM Catalog in 2015" -- this might suggest as if these records were only available in the RISM Catalog but not necessarily in RISM Online. So perhaps better "added to the online RISM database"?

**Review by BaMikusi — APPROVED** [review]
"cite the RISM ID number from the online catalog whenever possible" (line 70) - perhaps better "database" instead of "catalog" (to avoid further explanations at this point)

**Comment by jenniferward** [comment]
> We'll need to see if the statement in line 26 about a "collaboration" will be fine, for Laurent tended to refer to RO as being essentially a product of the DC.

I'll leave it out for now. 
All other changes made.

**Pull request merged**
