### PR TITLE
Update internships.de.md

### PR DESCRIPTION
**Pull request by HirschSt**

### CODE REVIEW

**Comment by ahankinson** [comment]
@HirschSt you should be able to merge this branch now; could you please check?

**Comment by HirschSt** [comment]
@ahankinson unfortunately it doesn't work: "The base branch restricts merging to authorized users."

**Comment by ahankinson** [comment]
@HirschSt you should have a pending invitation to the RISM digital group that you need to accept, and then you should have access

**Comment by HirschSt** [comment]
Now it works, thanks :thumbsup:

**Pull request merged**
