### PR TITLE
cat in_the_news Update 2020-07-23-the-music-for-richard-wagners-rienzi-preserved-in.md

### PR DESCRIPTION
**Pull request by jenniferward**

### CODE REVIEW

**Comment by jenniferward** [comment]
@ahankinson @lpugin I see that there is an error, but I don't know how to fix it!

**Comment by lpugin** [comment]
@jenniferward I can resolve the conflict. Which news category is the one you want?
```
<<<<<<< jenniferward-patch-4
category: in_the_news
=======
category: electronic_resources
>>>>>>> staging
```

**Comment by jenniferward** [comment]
in_the_news
Thank you!

**Comment by ahankinson** [comment]
@jenniferward is this ready to be merged now?

**Comment by jenniferward** [comment]
I don't know. It needs to have the category in_the_news. I haven't touched it since my initial edit 7 days ago.

**Comment by ahankinson** [comment]
If you look under the 'Files Changed' tab above, this seems to be OK?

**Comment by jenniferward** [comment]
Oh I see, thanks! Yes!

**Pull request merged**
